### ISSUE TITLE
Solve issue during modelling

### ISSUE THREAD

**Issue by jgusb** [mworion/MountWizzard3-DIST#6] opened 2018-06-21 20:43 UTC
Hi Michel

Log file...

[mount.2018-06-17.zip](https://github.com/mworion/MountWizzard3-DIST/files/2125262/mount.2018-06-17.zip)

Gus

**Comment by mworion** [comment] 2018-06-22 17:13
Hi Gus,

is that the log file with the situation you mentioned ? I can't see any try for modeling nor solving. There is only one error inside, where SGPro connection could not be established. I think SGPro didn't run.

Michel

**Comment by jgusb** [comment] 2018-06-22 20:23
Sorry Michel, my error, wrong file.  I believe it should be this one as it has the correct date on it. 

[mount.2018-06-21.zip](https://github.com/mworion/MountWizzard3-DIST/files/2129054/mount.2018-06-21.zip)

Gus

**Comment by jgusb** [comment] 2018-06-22 20:54
Or it might be this one - 

[mount.2018-06-20.zip](https://github.com/mworion/MountWizzard3-DIST/files/2129114/mount.2018-06-20.zip)

**Comment by mworion** [comment] 2018-06-22 21:14
Gus,

that's the right one. Question: you are using SGPro. Is during modeling the telescope driver connected ind SGPro ?

Michel

**Comment by jgusb** [comment] 2018-06-22 21:42
I'vve just run another test, same result. The first couple of failure to solve were my error - filters not set properly resultiming in an overexposure.  Again, Plate Solve and Sync Model works immediately, and also Expose 1 in the Image tab. 

[mount.2018-06-22.zip](https://github.com/mworion/MountWizzard3-DIST/files/2129233/mount.2018-06-22.zip)

Gus

**Comment by jgusb** [comment] 2018-06-22 21:45
Yes, everything is connected.  Also, I can see SGP working in the background as MW is using it.

Gus

**Comment by jgusb** [comment] 2018-06-23 06:49
Just to be clear;  at the beginning of each imaging sesion I start SGP and as I connect each piece of equipment the "Driver Connect" button changes colour from grey to orange to confirm Driver connection.  Whilst trying to model in MW I am able to see SGP on the Desktop and the Driver buttons all remain orange so I am sure the mount is remaining connected all the way through.  Also, at any time I can manually Solve/sync in both SGP and MW indicating Connection to the mount must be constant.

**Comment by mworion** [comment] 2018-06-23 15:20
Gus,
understood. The reason why should be clear: the starting coordinates for solving are not good. I took them out of the FITS header (that's why I'm asked). Still I worked with SGPro and I have not seen you issues, but it is not your fault.
I made a test version link: 
https://www.dropbox.com/s/yqn79ovgdmo9zmv/mountwizzard3-console-3.0b8.dev0.exe?dl=0
where the behavior is changed (I now write in all cases the mount coordinates in the FITS header)
Michel

**Comment by jgusb** [comment] 2018-06-24 21:31
Hi Michel 
No Progress i'm afraid -  MW08 seems to behave ibn exactly the same way as 07.  If I run a one point model it will Solve immediately but any more than one point and it will only solve the last one.  As before, "Expose 1" solves ok as does "Plate Solve and Sync Model"

[mount.2018-06-24.zip](https://github.com/mworion/MountWizzard3-DIST/files/2131222/mount.2018-06-24.zip)

Gus

**Comment by jgusb** [comment] 2018-06-25 22:07
Michel,

One thought....

Should I have set the 10 Micron mount driver to Refines?? It is currently set to Align and could that cause the problem?

Gus

**Comment by mworion** [comment] 2018-06-26 00:04
Hi Gus,

I will check the log file, when I‘m back from Texas ( it‘s really warm there). MW does not use the driver and does not switch between refine and align as it uses now a model building procedure which is not incremental. 

The issue at your setup arises, because during model build the start point for solving is bad. I could not reproduce that in INDIsimulation environment, I need to wait until I could use SGPro under real stars. 

Michel

**Comment by mworion** [comment] 2018-06-28 18:48
Hi Gus,

did another try. Still not able to catch your issue. 2 times not solving, but when still standing yes. Added more logging. Found minor topics, but the should not be related to your point.
Download: https://www.dropbox.com/s/ofgcu09a7pzwwmd/mountwizzard3-console-3.0b8.dev1.exe?dl=0
Michel

**Comment by mworion** [comment] 2018-07-06 12:04
Hi Gus,

anything news about the situation ?

**Comment by jgusb** [comment] 2018-07-06 21:54
Hi Michel

 

I have not been able to run the observatory over the past few days.  I have just run the same test as I ran before – it seems to give the same results, i.e. will only solve the last point on a multipoint model but will Plate Solve and Sync Model okay and will solve an Expose 1 frame okay.

 

Files attached – hope they are the right ones!

 

Gus

**Comment by mworion** [comment] 2018-07-24 20:07
Hi Gus,

as I got two more feedbacks about the problem you had. Michel-d checked out probably the difference. So I made beta 10 which should solve the issue. If you could test it and feed back, that would be nice.

CS

Michel

**Comment by jgusb** [comment] 2018-07-25 21:37
Hi Michel

 

A few problems with beta 10…

 

Superficially it looks as if MW has connected to everything okay, however:

 

1.       On the Mount Data tab the slew rate is not populated,

2.       On the Site Data tab, Data in Mount is not populated, yet the RA and Dec are updating okay as is the Local Sidereal Time and the Julian Date.

3.       When clicking either Plate Solve and Sync Model or Expose 1 no connection is made to the camera - SGPro does not activate and after a couple of minutes I get a Timeout Connection to Camera warning in the Message window.

4.       If I load FITS image from file on the Image window it will then Solve.

 

It would therefore seem that the link between MW and SGPro camera is broken?

 

Having tried all the above several times I then reverted to MW 8 -  all the above functions worked perfectly.  The only thing MW 8 will not do is Solve during Model runs (except the last point each time). 

 

I am interested to know that some others have also had this issue.

 

Regards

 

Gus

**Comment by jgusb** [comment] 2018-07-26 13:37
Hi Michel

 

Ok.  I will download beta 11 today and test it tonight if I can, although thunderstorms are forecast over the next few evenings so it may not be until next week.

 

Gus

**Comment by jgusb** [comment] 2018-07-26 13:59
Michel, 
I am having trouble downloading Beta 11 - there doesn't seem to be a "Download" button for it?

Gus

**Comment by mworion** [comment] 2018-07-26 16:36
Gus,

Seem that GitHub changed their policy about download of binary files. Actually you will find it at

https://www.dropbox.com/sh/vj0dnd4aue81z8m/AACX-BsnC6NuQwP_dyQf5lvAa?dl=0

Have to clearify that.

Michel

**Comment by mworion** [comment] 2018-07-28 11:36
Gus,

...should be OK by now again on GitHub. Please find them under
https://github.com/mworion/MountWizzard3-DIST/releases 
always the latest ones. michel-d had found some problems in beta11dev0 not clearing all the fits headers. this is corrected in beta11dev1

Michel

**Comment by jgusb** [comment] 2018-08-01 09:40
Hi Michel

3.0 11 dev1  seems to work okay!  I ran Initial and Full models last night and all the points seemed to solve okay.  I have attached the log.  One query:  Normally, solve solutions are expressed as co-ordinates for RA and Dec in the Messages window but I noticed last night that solutions during modelling seem to be expressed as "diff..."  can you explain what that means?  The model seems to be accurate - it came out at 7" RMS and a subsequent image of M92 was absolutely right in the middle of the frame.  The only slight issue seems to be with the "Plate Solve and Sync Model" button, which didn't seem to complete the task.  I will check that again tonight.  If this version is robust and reliable then I think you have a fabulous piece of software and one which I am delighted to have access to.  Thank you very much for your hard work and perseverance!

[mount.2018-07-31.zip](https://github.com/mworion/MountWizzard3-DIST/files/2248871/mount.2018-07-31.zip)

**Comment by mworion** [comment] 2018-08-01 11:58
Hi Gus,

thanks for reporting back. So far I see in the log, that my final assumption were right. I have to correct the RA / DEC values when model build, because SGPro enters these ones to late when the mount already is in slewing mode. But that I recognized early. In addition SGPro writes more than one FITS header entries with different Labels for that values and give them higher priority when looking for a plate solve hint. So removing them makes SGPro solving now. 

I've seen a bug entry in plate solve / sync that will be corrected by beta 12. This will be online in an hour.

A second bug is in there (and you might not discover it from standard usage), which is related to (at least from my point of view) a bug in the mount computer. I already have addressed that to Filippo, but have no answer so far.  

As far as this issue is concerned I would like to close it. If you discover other issues, please open another one (helps to keep order).

Michel

**Closed** 2018-08-01 12:00 UTC
Labels: bug
